### ISSUE TITLE
Inefficient emoticons cleaning

### ISSUE THREAD

**Issue by twitu** [MananSoni42/ML-SIG-2018#1]
https://github.com/MananSoni42/ML-SIG-2018/blob/abd4848ba7500cace67592cd81c447d81d3f721d/clean_tweets/cleanTweets.py#L98-L109

Your code iterates over all emoticons for each character in the tweet in line 108. This is highly inefficient for a library that will process millions of characters. Use a dictionary to store your emoticons.

**Comment by twitu** [comment]
Same goes for this part of the code:
https://github.com/MananSoni42/ML-SIG-2018/blob/abd4848ba7500cace67592cd81c447d81d3f721d/clean_tweets/cleanTweets.py#L172-L173

**Comment by twitu** [comment]
In fact this is poorly designed code. Your lists containing emoticons, non-alphabetic characters (which should be in dictionaries) are a part of your class Tweet. They are invariable over many instances of Tweet you create.

You should declare them as static class variables instead of re declaring them each time a function in called.

**Comment by MananSoni42** [comment]
I have modified the functions to use sets instead of lists and made the emoticons and punctuation static variables.

**Comment by twitu** [comment]
Can you post the results of the timing tests here, so as to compare the two different implementations.

**Comment by MananSoni42** [comment]
This commit:
DEBUG: spellCorrect ran in 0.18s
DEBUG: defaultClean ran in 0.18s

earlier commit:
DEBUG: spellCorrect ran in 0.2s
DEBUG: defaultClean ran in 0.2s

**Comment by twitu** [comment]
Great this I am closing this issue.
Do include your timing results for a large dataset in your README

**Comment by twitu** [comment]
Great I am closing this issue with reference to the commit 2f3a6df
You should include the timings for a large dataset in your README.
